"use client";
import React from "react";
import PageContainer from "@/components/ui/PageContainer";
import ProfileHeader from "@/components/ui/ProfileHeader";
import ReferralSection from "@/components/ui/ReferralSection";
import QuestCard from "@/components/ui/QuestCard";
import StatsSection from "@/components/ui/StatsSection";
import GradientButton from "@/components/ui/GradientButton";
import TelegramCard from "@/components/ui/TelegramCard";

export default function ProfilePage() {
  const questsData = [
    {
      id: 1,
      type: 'Refer',
      title: "Refer 2 People",
      description: "Refer 2 people to complete this quest.",
      progress: 2,
      target: 2,
      status: "complete" as const,
    },
    {
      id: 2,
      type: 'Generate',
      title: "Generate 3 Volume",
      description: "3 Volume to complete this quest.",
      progress: 3,
      target: 3,
      status: "complete" as const,
    },
    {
      id: 3,
      type: 'Reach',
      title: "Reach 56 PNL",
      description: "56 PNL to complete this quest.",
      progress: 56,
      target: 56,
      status: "complete" as const,
    },
  ];

  const statsData = [
    {
      id: 1,
      title: "Total claimed",
      value: "1633",
    },
    {
      id: 2,
      title: "Referrals",
      value: "12",
      subtitle: "Total Invited",
    },
    {
      id: 3,
      title: "Volume",
      value: "3200 SOL",
      subtitle: "Generated by referrals",
    },
    {
      id: 4,
      title: "Rewards",
      value: "8.5 SOL",
      subtitle: "Earned from referrals",
    },
  ];

  const handleClaimReward = () => {
    console.log("Claim Reward clicked!");
    // Implement claim logic here
  };

  return (
    <PageContainer>
      <div className="flex flex-col gap-8">
        {/* Profile Header with Score */}
        <TelegramCard username="Spades" connected={true} />

        <ProfileHeader score={0} nextLevel="Refer 2 more users to earn more points." />
        
        {/* Referral Section */}
        <ReferralSection />
        
        {/* Quests Section */}
        <div className="space-y-4">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            {questsData.map((quest) => (
              <QuestCard
                type={quest.type}
                key={quest.id}
                title={quest.title}
                description={quest.description}
                progress={quest.progress}
                target={quest.target}
                status={quest.status}
              />
            ))}
          </div>
        </div>
        
        {/* Stats Section */}
        <StatsSection stats={statsData} />
        
        {/* Claim Reward Button */}
        <div className="flex pt-6">
          <GradientButton
            label="Claim Reward"
            onClick={handleClaimReward}
            gradient="linear-gradient(0deg, #5A43C6, #8761FF)"
            hoverGradient="linear-gradient(0deg, #4A36B0, #765FE0)"
            className="h-10 w-40"
          />
        </div>
      </div>
    </PageContainer>
  );
}
